import * as THREE from 'three';
import {createPourRig,pourFill} from './pouring.js';
import {OrbitControls} from './vendor/OrbitControls.js';
import {recipes,ingredients,stagesFor,fillAt,liquidTotal} from './recipes.js';
const $=s=>document.querySelector(s),host=$('#scene');
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
const state={recipe:recipes[0],progress:1,playing:false,speed:1,mixed:false,mix:0,filter:'all',step:''};
let renderer;
try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});}catch(e){$('#loading').textContent='The 3D glass needs WebGL. Enable hardware acceleration or try another browser.';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0,0);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;host.append(renderer.domElement);$('#loading').remove();renderer.domElement.setAttribute('aria-label','Interactive glass showing the ingredients of the selected kopi. Drag to rotate.');
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(36,1,.1,70),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=6;controls.maxDistance=13;controls.minPolarAngle=.45;controls.maxPolarAngle=1.55;
function resetCamera(){camera.position.set(4.1,4.6,7.8);controls.target.set(0,1.9,0);controls.update();}resetCamera();
scene.add(new THREE.HemisphereLight(0xfff8e6,0xac8060,3.5));const key=new THREE.DirectionalLight(0xfff7e7,3);key.position.set(-3,7,4);key.castShadow=true;key.shadow.mapSize.set(1024,1024);Object.assign(key.shadow.camera,{left:-5,right:5,top:6,bottom:-4,near:.1,far:25});key.shadow.normalBias=.03;scene.add(key);const rim=new THREE.DirectionalLight(0xffffff,2.5);rim.position.set(4,4,-3);scene.add(rim);
const root=new THREE.Group();scene.add(root);
const ceramic=new THREE.MeshStandardMaterial({color:0xfaf4e8,roughness:.38,metalness:.05}),glass=new THREE.MeshPhysicalMaterial({color:0xd8f2eb,roughness:.12,metalness:.1,transparent:true,opacity:.16,side:THREE.DoubleSide,depthWrite:false}),glassEdge=new THREE.MeshStandardMaterial({color:0xddece4,roughness:.15,metalness:.35,transparent:true,opacity:.65,depthWrite:false});
function mesh(g,mat,x=0,y=0,z=0,parent=root){const m=new THREE.Mesh(g,mat);m.position.set(x,y,z);parent.add(m);return m;}
function cylinder(rt,rb,h,mat,x=0,y=0,z=0,parent=root){return mesh(new THREE.CylinderGeometry(rt,rb,h,64),mat,x,y,z,parent);}
function torus(r,t,mat,x,y,z,parent=root){const m=mesh(new THREE.TorusGeometry(r,t,12,80),mat,x,y,z,parent);m.rotation.x=Math.PI/2;return m;}
const saucer=cylinder(1.58,1.38,.13,ceramic,0,.04,0);saucer.receiveShadow=true;torus(1.47,.042,ceramic,0,.10,0);torus(1.31,.017,new THREE.MeshStandardMaterial({color:0xa35d3b,roughness:.4}),0,.115,0);cylinder(1.13,1.1,.08,ceramic,0,.13,0);
const profile=[[0,.19],[.98,.19],[1.05,.26],[1.05,3.15],[1.01,3.19],[.98,3.15],[.98,.34],[0,.34]].map(p=>new THREE.Vector2(...p));const cup=mesh(new THREE.LatheGeometry(profile,96),glass);cup.renderOrder=10;
torus(1.025,.037,glassEdge,0,3.16,0).renderOrder=11;torus(1.005,.045,glassEdge,0,.29,0).renderOrder=11;
const handlePath=new THREE.CatmullRomCurve3([new THREE.Vector3(1.02,2.6,0),new THREE.Vector3(1.68,2.57,0),new THREE.Vector3(1.85,1.85,0),new THREE.Vector3(1.68,1.03,0),new THREE.Vector3(1.02,1.0,0)]);const handle=mesh(new THREE.TubeGeometry(handlePath,48,.11,12,false),glassEdge);handle.renderOrder=11;
// Thin vertical highlights keep the clear glass legible without obscuring its contents.
for(const angle of [-.8,1.9]){const path=new THREE.LineCurve3(new THREE.Vector3(Math.cos(angle)*1.05,.42,Math.sin(angle)*1.05),new THREE.Vector3(Math.cos(angle)*1.05,3.01,Math.sin(angle)*1.05));const h=mesh(new THREE.TubeGeometry(path,1,.014,6,false),new THREE.MeshBasicMaterial({color:0xffffff,transparent:true,opacity:.6,depthWrite:false}));h.renderOrder=12;}
const liquidKeys=['condensed','evaporated','coffee','water'];const liquids={};
for(const k of liquidKeys){const mat=new THREE.MeshStandardMaterial({color:ingredients[k].color,roughness:.4,metalness:0});liquids[k]=cylinder(.962,.962,1,mat);liquids[k].castShadow=false;}
const blended=cylinder(.963,.963,1,new THREE.MeshStandardMaterial({color:0x8d5834,roughness:.28}));blended.visible=false;
const iceGroup=new THREE.Group();root.add(iceGroup);const iceMat=new THREE.MeshPhysicalMaterial({color:0xd6eff4,roughness:.17,metalness:.12,transparent:true,opacity:.8,depthWrite:false});const ice=[];for(let i=0;i<6;i++){const m=mesh(new THREE.BoxGeometry(.37,.34,.38),iceMat,0,0,0,iceGroup);m.rotation.set(i*.4,.3+i*.8,.2+i*.3);m.renderOrder=5;ice.push(m);}
const sugar=[];for(let i=0;i<8;i++){const m=mesh(new THREE.BoxGeometry(.14,.14,.14),new THREE.MeshStandardMaterial({color:0xfff8df,roughness:1}),0,0,0);sugar.push(m);}
const pourRig=createPourRig(root);
const metal=new THREE.MeshStandardMaterial({color:0xb6b9b1,roughness:.3,metalness:.8});
const spoon=new THREE.Group();root.add(spoon);const bowl=mesh(new THREE.SphereGeometry(.16,20,12),metal,0,4.0,0,spoon);bowl.scale.set(1.4,.3,1);const spoonHandle=mesh(new THREE.BoxGeometry(.65,.035,.065),metal,-.42,4.03,0,spoon);spoon.visible=false;
const falling=[];for(let i=0;i<9;i++)falling.push(mesh(new THREE.BoxGeometry(.07,.07,.07),new THREE.MeshStandardMaterial({color:0xfbf2db}),0,0,0));
const steam=[];for(let i=0;i<3;i++){const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(new Float32Array(24*3),3));const line=new THREE.Line(geo,new THREE.LineBasicMaterial({color:0xffffff,transparent:true,opacity:.4,depthWrite:false}));root.add(line);steam.push(line);}
const shadow=mesh(new THREE.PlaneGeometry(30,30),new THREE.ShadowMaterial({opacity:.1}),0,-.04,0,scene);shadow.rotation.x=-Math.PI/2;shadow.receiveShadow=true;
let width=1,height=1;function resize(){width=host.clientWidth;height=host.clientHeight;renderer.setSize(width,height,false);camera.aspect=width/height;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe(host);resize();
function renderMenu(){const list=$('#menu-list');list.replaceChildren();recipes.forEach((r,i)=>{if(state.filter!=='all'&&r.family!==state.filter)return;const b=document.createElement('button');b.className='coffee-option'+(r.id===state.recipe.id?' active':'');b.setAttribute('aria-pressed',String(r.id===state.recipe.id));b.innerHTML=`<span class="number">${String(i+1).padStart(2,'0')}</span><span><strong>${r.name}</strong><small>${r.family==='iced'?'Over ice':r.amounts.condensed?'Condensed milk':r.amounts.evaporated?'Evaporated milk':'Black coffee'}</small></span><span class="dot"></span>`;b.addEventListener('click',()=>selectRecipe(r));list.append(b);});}
function setView(mixed){state.mixed=mixed;$('#mixed').classList.toggle('active',mixed);$('#layers').classList.toggle('active',!mixed);$('#mixed').setAttribute('aria-pressed',String(mixed));$('#layers').setAttribute('aria-pressed',String(!mixed));$('#view-note').textContent=mixed?'Blended colour is illustrative':'Separated layers for illustration';}
function selectRecipe(r){state.recipe=r;state.progress=1;state.playing=false;state.step='';$('#glass-name').textContent=r.name;$('#glass-number').textContent=String(recipes.indexOf(r)+1).padStart(2,'0');$('#glass-desc').textContent=r.desc;$('#recipe-title').textContent=r.name;$('#recipe-desc').textContent=r.desc;$('#temperature').textContent=r.amounts.ice?'ICED / 冰':'HOT / 热';$('#recipe-note').textContent=r.note;const list=$('#ingredient-list');list.replaceChildren();for(const k of stagesFor(r)){const row=document.createElement('div');row.className='ingredient';row.innerHTML=`<span class="swatch" style="background:${ingredients[k].color}"></span><span>${ingredients[k].name}</span><span class="amount">${r.amounts[k]} ${ingredients[k].unit}</span>`;list.append(row);}const stepList=$('#step-list');stepList.replaceChildren();const stages=stagesFor(r);stages.forEach((k,i)=>{const b=document.createElement('button');b.textContent=`${i+1}. ${ingredients[k].name}`;b.addEventListener('click',()=>{state.playing=false;state.progress=(i+.55)/stages.length;updateUI();});stepList.append(b);});renderMenu();updateUI();}
function updateUI(){const stages=stagesFor(state.recipe),i=Math.min(stages.length-1,Math.floor(state.progress*stages.length));const text=state.progress>=1?'Your kopi is ready':`Step ${i+1}/${stages.length} · ${ingredients[stages[i]].verb}`;if(text!==state.step){$('#step-status').textContent=text;state.step=text;}$('#progress').value=Math.round(state.progress*1000);$('#progress-text').textContent=Math.round(state.progress*100)+'%';$('#play').textContent=state.playing?'Ⅱ':'▶';$('#play').setAttribute('aria-label',state.playing?'Pause preparation':state.progress>=1?'Replay preparation':'Continue preparation');$('#step-list').querySelectorAll('button').forEach((b,j)=>b.classList.toggle('current',j===i&&state.progress<1));}
function start(){state.progress=0;state.playing=true;state.step='';setView(false);updateUI();}
$('#make').addEventListener('click',start);$('#play').addEventListener('click',()=>{if(state.progress>=1)start();else {state.playing=!state.playing;updateUI();}});$('#progress').addEventListener('input',e=>{state.playing=false;state.progress=Number(e.target.value)/1000;updateUI();});$('#speed').addEventListener('change',e=>state.speed=Number(e.target.value));$('#layers').addEventListener('click',()=>setView(false));$('#mixed').addEventListener('click',()=>setView(true));$('#reset-camera').addEventListener('click',resetCamera);document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{state.filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});renderMenu();}));
selectRecipe(recipes[0]);
const baseColors=Object.fromEntries(liquidKeys.map(k=>[k,new THREE.Color(ingredients[k].color)]));const coffeeColor=new THREE.Color('#3c1809'),milkColor=new THREE.Color('#c8955d'),waterBlend=new THREE.Color('#673519'),mixColor=new THREE.Color();let previous=performance.now();
function frame(now){const dt=Math.min((now-previous)/1000,.05);previous=now;const t=now/1000,r=state.recipe,stages=stagesFor(r),n=stages.length;
 if(state.playing){state.progress=Math.min(1,state.progress+dt*state.speed/(n*1.7));if(state.progress===1)state.playing=false;updateUI();}
 state.mix=THREE.MathUtils.lerp(state.mix,state.mixed?1:0,reduced.matches?1:1-Math.exp(-dt*6));
 const fractions=Object.fromEntries(Object.keys(ingredients).map(k=>[k,r.amounts[k]>0?fillAt(state.progress,stages.indexOf(k),n):0]));
 const amounts=Object.fromEntries(liquidKeys.map(k=>[k,r.amounts[k]*pourFill(fractions[k])]));const volume=Object.values(amounts).reduce((a,b)=>a+b,0),iceDisplace=r.amounts.ice*7*fractions.ice;
 const milk=amounts.condensed+amounts.evaporated;mixColor.copy(coffeeColor).lerp(waterBlend,volume?amounts.water/volume*.65:0).lerp(milkColor,volume?Math.min(.85,milk/volume*3.5):0);
 let y=.35;for(const k of liquidKeys){const h=amounts[k]*.0108*(volume?1+iceDisplace/volume:1),m=liquids[k];m.visible=h>.001&&state.mix<.995;m.scale.y=Math.max(.001,h);m.position.y=y+h/2;m.material.color.copy(baseColors[k]).lerp(mixColor,state.mix);y+=h;}
 blended.visible=volume>0&&state.mix>=.995;blended.scale.y=Math.max(.001,y-.35);blended.position.y=(y+.35)/2;blended.material.color.copy(mixColor);
 for(let i=0;i<ice.length;i++){const q=THREE.MathUtils.clamp(fractions.ice*6-i,0,1);ice[i].visible=q>0;const a=i*2.399;ice[i].position.set(Math.cos(a)*(.35+i*.05),y-.09+(1-q)*2.3+(!reduced.matches&&state.progress===1?Math.sin(t*1.3+i)*.025:0),Math.sin(a)*(.35+i*.05));ice[i].scale.setScalar(Math.min(1,q*4));}
 for(let i=0;i<sugar.length;i++){const q=Math.min(1,r.amounts.sugar/2-i);sugar[i].visible=q>0&&fractions.sugar>0;const dissolve=1-Math.min(1,(fractions.coffee+fractions.water)*.95+state.mix);sugar[i].scale.setScalar(Math.max(.001,dissolve*Math.min(1,fractions.sugar*4)));sugar[i].position.set(Math.cos(i*2.4)*.55,.43,Math.sin(i*2.4)*.55);}
 const activeIndex=Math.min(n-1,Math.floor(state.progress*n)),active=stages[activeIndex],f=fractions[active],pouring=state.progress>0&&state.progress<1&&f>.02&&f<.98;
 pourRig.update(active,state.progress<1?f:1,y);spoon.visible=pouring&&active==='sugar';
 for(let i=0;i<falling.length;i++){falling[i].visible=pouring&&active==='sugar';const phase=(t*1.4+i*.117)%1;falling[i].position.set(Math.sin(i*3)*.17,4-phase*3.6,Math.cos(i*3)*.17);}
 for(let i=0;i<steam.length;i++){steam[i].visible=!r.amounts.ice&&state.progress>=1&&!reduced.matches;const a=steam[i].geometry.attributes.position;for(let j=0;j<24;j++){const v=j/23;a.setXYZ(j,(i-1)*.4+Math.sin(v*6+t*1.1+i)*.06,y+.08+v*.65,Math.cos(v*5+t+i)*.06);}a.needsUpdate=true;}
 controls.update();renderer.render(scene,camera);
}
renderer.setAnimationLoop(frame);renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();renderer.setAnimationLoop(null);const p=document.createElement('p');p.id='loading';p.textContent='The 3D display was interrupted. Reload to restore your glass.';host.append(p);});
